---
title: "French Trains"
author: "Thinh"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
theme_set(theme_light())

full_trains <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-26/full_trains.csv") %>% 
    mutate(departure_station = str_to_title(departure_station),
         arrival_station = str_to_title(arrival_station),
         pct_late_at_departure = num_late_at_departure/total_num_trips) %>% 
  mutate(month = make_date(year, month))

```


```{r}
november_2018 <- full_trains %>% 
  filter(month == "2018-11-01") 

november_2018 %>% 
  ggplot(aes(pct_late_at_departure)) + 
  geom_histogram(binwidth = 0.05) + 
  scale_x_continuous(labels = scales::percent_format())

november_2018 %>% 
  mutate(departure_station = fct_lump(departure_station, 3)) %>% 
  ggplot(aes(departure_station, pct_late_at_departure)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::percent_format())


november_2018 %>% 
  mutate(arrival_station = fct_reorder(fct_lump(arrival_station, prop = .01), pct_late_at_departure),
         departure_station = fct_reorder(fct_lump(departure_station, prop = .01), pct_late_at_departure)) %>% 
  group_by(arrival_station, departure_station) %>% 
  summarise(pct_late_at_departure = sum(num_late_at_departure)/ sum(total_num_trips)) %>% 
  ggplot(aes(arrival_station, departure_station, fill = pct_late_at_departure)) +
  geom_tile() + 
  scale_fill_gradient2(low = "blue", 
                       high = "red", 
                       midpoint = 0.25, 
                       labels = scales::percent_format()) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    x = "Arrival tation",
    y = "Departure station",
    fill = "% late at departure",
    title = "Which route has the most deplayed trains in November 2018",
    subtitle = "Stations with only one arriving/departing route are lumped in to 'Other' "
  )
```


### Over time 

```{r}
by_departure_station_month <- full_trains %>%
  # mutate(departure_station = fct_lump(departure_station, prop = .02)) %>% %
  group_by(departure_station, month) %>% 
  summarise(across(contains("num"), sum)) %>% 
  ungroup() %>% 
  mutate(pct_late_at_departure = num_late_at_departure/total_num_trips) 

by_departure_station_month  %>% 
  mutate(departure_station = fct_reorder(departure_station, -pct_late_at_departure, last)) %>% 
  ggplot(aes(month, pct_late_at_departure, colour = departure_station)) +
  geom_line() + 
  expand_limits(y = 0) + 
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(
    x = "Month",
    y = "% late at departure",
    colour = "Departure station"
  )

by_departure_station_month %>% 
  mutate(departure_station = fct_reorder(departure_station, pct_late_at_departure)) %>% 
  ggplot(aes(month, departure_station, fill = pct_late_at_departure)) + 
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", midpoint = .25, labels = scales::percent_format()) +
  labs(
    fill = "% late at departure"
  )
```

