---
title: "The Office"
author: "Thinh"
date: "8/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())
```

# Explore data

```{r}
ratings_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv")

View(ratings_raw)
```

```{r}
ratings_raw %>% 
  count(title, sort=TRUE)

ratings_raw %>% 
  count(imdb_rating, sort=TRUE) %>% 
  ggplot(aes(imdb_rating, n)) + 
  geom_col()
```

```{r}
# cleaning 
remove_regex <- "[:punct:]|[:digit:]|parts |part |the |and"
office_ratings<- ratings_raw %>% 
  transmute(episode_name = str_to_lower(title), # lower characters
            episode_name =  str_remove_all(episode_name, remove_regex), # remove part
            episode_name = str_trim(episode_name),# remove white space
            imdb_rating)


office_info <- schrute::theoffice %>% 
  mutate(season = as.numeric(season),
         episode = as.numeric(episode),
         episode_name = str_to_lower(episode_name), # lower characters
         episode_name =  str_remove_all(episode_name, remove_regex), # remove part
         episode_name = str_trim(episode_name)) %>% 
  select(season, episode, episode_name, director, writer, character)
```

```{r}
# Characters 
office_info %>% 
  count(character, sort = TRUE) %>% 
  filter(n > 800) %>%
  mutate(character = fct_reorder(character, n)) %>% 
  ggplot(aes(character, n)) + 
  geom_col() + 
  labs(
    title = "The top character having the most lines of conversation",
    subtitle = "More than 500 lines of the whole series",
    x = "Character",
    y = "Number of lines"
  ) +
  theme(legend.position = "None") +
  coord_flip() 
```

```{r}
# Characters per episode 
characters <- office_info %>% 
  count(episode_name, character, sort=TRUE) %>% 
  add_count(character, wt = n, name = "character_count") %>% 
  filter(character_count > 800) %>% 
  select(-character_count) %>% 
  pivot_wider(names_from = character,
              values_from = n,
              values_fill = list(n = 0))
```

```{r}
creators <- office_info %>% 
  distinct(episode_name, director, writer) %>% 
  pivot_longer(director:writer, names_to = "role", values_to = "person") %>% 
  separate_rows(person, sep = ";") %>%  # split names in to different rows
  add_count(person) %>% # too crowd persons
  filter(n > 10) %>%  # only who involve more than 10 episodes
  distinct(episode_name, person) %>% 
  mutate(person_value = 1) %>% 
  pivot_wider(names_from = person, 
              values_from = person_value,
              values_fill = list(person_value = 0))

office <- office_info %>% 
  distinct(season, episode, episode_name) %>% 
  inner_join(characters) %>% 
  inner_join(creators) %>% 
  inner_join(office_ratings %>%
               select(episode_name, imdb_rating)) %>% 
  janitor::clean_names()
``` 

```{r}
office %>% 
  ggplot(aes(episode, imdb_rating, fill = as.factor(episode))) + 
  geom_boxplot(show.legend =  FALSE)
```


# Train a model 

```{r}
library(tidymodels)
office_split <- initial_split(office, strata = season) # equally season in test and train
office_train <- training(office_split)
office_test <- testing(office_split)
```


```{r}
office_rec <- recipe(imdb_rating ~ ., data = office_train) %>% 
  update_role(episode_name, new_role = "ID") %>% 
  step_zv(all_numeric(), all_outcomes()) %>% 
  step_normalize(all_numeric(), -all_outcomes())

office_prep <- office_rec %>% 
  prep(strings_as_factors = FALSE)
```

```{r}
lasso_spec <- linear_reg(penalty = .1, mixture = 1) %>% 
  set_engine("glmnet")


wf <- workflow() %>% 
  add_recipe(office_rec)
  
lasso_fit <- wf %>% 
  add_model(lasso_spec) %>% 
  fit(data = office_train)

lasso_fit %>% 
  pull_workflow_fit() %>% 
  tidy()
```


## Tune Lasso parameters

```{r}
set.seed(1234)
office_boot <- bootstraps(office_train, strata = season)

tune_spec <- linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

lambda_grid <- grid_regular(penalty(),
             levels = 50)

doParallel::registerDoParallel()

set.seed(2020)
lasso_grid <- tune_grid(
  wf %>% add_model(tune_spec),
  resamples = office_boot,
  grid = lambda_grid
)

```

```{r}
lasso_grid %>% 
  collect_metrics() %>% 
  ggplot(aes(penalty, mean, color = .metric)) + 
  geom_errorbar(aes(ymin = mean - std_err,
                    ymax = mean + std_err,
                    alpha = 0.5)) +
  geom_line(size = 1.5) + 
  facet_wrap(~ .metric, scales = "free", nrow = 2) + 
  scale_x_log10() +
  theme(legend.position = "none")
```


```{r}
lowest_rmse <- lasso_grid %>% 
  select_best("rmse", maximize = FALSE)

final_lasso <- finalize_workflow(wf %>% add_model(tune_spec),
                                 lowest_rmse)

library(vip)

final_lasso %>% 
  fit(office_train) %>% 
  pull_workflow_fit() %>% 
  vi(lambda = lowest_rmse$penalty) %>% 
  mutate(Importance = abs(Importance),
         Variable = fct_reorder(Variable, Importance)) %>% 
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) + 
  geom_col() + 
  scale_x_continuous(expand = c(0,0)) + 
  labs(y = NULL)
```

