---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler")
```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-05-19')
vb_matches <- tuesdata$vb_matches
```

```{r}
theme_plex <- function(base_size = 11,
                       strip_text_size = 12,
                       strip_text_margin = 5,
                       subtitle_size = 13,
                       subtitle_margin = 10,
                       plot_title_size = 16,
                       plot_title_margin = 10,
                       ...) {
    ret <- ggplot2::theme_minimal(base_family = "IBMPlexSans",
                                  base_size = base_size, ...)
    ret$strip.text <- ggplot2::element_text(hjust = 0, size=strip_text_size,
                                            margin=margin(b=strip_text_margin),
                                            family="IBMPlexSans-Medium")
    ret$plot.subtitle <- ggplot2::element_text(hjust = 0, size=subtitle_size,
                                               margin=margin(b=subtitle_margin),
                                               family="IBMPlexSans")
    ret$plot.title <- ggplot2::element_text(hjust = 0, size = plot_title_size,
                                            margin=margin(b=plot_title_margin),
                                            family="IBMPlexSans-Bold")
    ret
}

```

```{r}
library(tidyverse)
theme_set(theme_light())
```

```{r}
vb_matches %>% 
  count(circuit, date) %>% 
  ggplot(aes(date, n, colour = circuit)) +
  geom_line()
```

